---
contentdir: "content"
layoutdir: "layouts"
publishdir: "public"
builddrafts: false
theme: "lanyon-hugo"
baseurl: "https://www.dragonsreach.it"
canonifyurls: true
permalinks:
  post: ":year/:month/:day/:title/"
  fixed: ":title/"
markup:
  goldmark:
    extensions:
      typographer: true
    renderer:
      unsafe: true
pygmentsuseclasses: true
menu:
  main:
  - identifier: "tags"
    name: "Categories"
    title: "Categories"
    url: "/categories/"
    weight: -1
  - identifier: "about-me"
    name: "About me"
    title: "About me"
    url: "/about-me/"
    weight: 0
params:
  Title: "Andrea Veri's Blog"
  Tagline: "Me, myself and I"
  Author: "Andrea Veri"
  DateForm: "Jan 2, 2006"
  description: "Andrea Veri's Blog"
  mainSections:
  - "post"
  disableFonts: false
paginate: 5
