---
contentdir: "content"
layoutdir: "layouts"
publishdir: "public"
builddrafts: false
theme: "beauty"
baseurl: "https://www.dragonsreach.it"
title: "Andrea Veri's Blog"

markup:
  goldmark:
    extensions:
      typographer: true
    renderer:
      unsafe: true
pygmentsuseclasses: true

permalinks:
  post: ":year/:month/:day/:title/"
  fixed: ":title/"
  categories: "/categories/:slug/"

params:
  description: "Andrea Veri's Blog"
  tagline: "Me, myself and I"
  author:
    name: "Andrea Veri"
  website:
    sources: "https://github.com/averi/dragonsreach.it"
