baseurl: https://www.dragonsreach.it
name: "Andrea Veri's Blog"
description:
theme: 'beautifulhugo'
title: "Andrea Veri's Blog"
pygmentsCodeFences: true
pygmentsStyle: "friendly"
#googleanalytics: UA-34660847-2

params:
    subtitle: Me, Myself and I
    rss: true
    mainSections:
     - "post"
     - "posts"

menu:
  main:
    - name: "About me"
      url: "/about-me"
      weight: 0

author:
  twitter: andrea_veri
  linkedin: andrea-veri-bb23a091
  name: Andrea Veri
  website: https://www.dragonsreach.it
